# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QRCodeBeachmark' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'NNMacros'
  pod 'OpenCV2',        '4.0.1'
  pod 'ZBarSDK',        '1.3.1'
  pod 'ZXingObjC',      '3.6.5'
  pod 'GoogleMLKit/BarcodeScanning',    '0.62.0'
  pod 'Quirc',          :path => './Thirdparty/Quirc/'
  
  target 'QRCodeBeachmarkTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'QRCodeBeachmarkUITests' do
    # Pods for testing
  end
  
end
