# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QRCodeBeachmark' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Masonry'
  pod 'OpenCV'
  pod 'ZBarSDK'
  pod 'ZXingObjC'
  pod 'GoogleMLKit/BarcodeScanning'
  pod 'NNMacros'
  
  
  target 'QRCodeBeachmarkTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'QRCodeBeachmarkUITests' do
    # Pods for testing
  end
  
end
